FROM neo4j:5.4.0

COPY conf/apoc.conf /var/lib/neo4j/conf
COPY conf/neo4j.conf /var/lib/neo4j/conf
COPY tabby-path-finder-1.1.jar /var/lib/neo4j/plugins
COPY apoc-5.4.0-extended.jar /var/lib/neo4j/plugins
COPY apoc-5.4.1-core.jar /var/lib/neo4j/plugins